#==========================================================================
# Description: Build Armbian For rockchip boxes
# Copyright (C) 2021 https://github.com/ophub/rockchip-armbian
#==========================================================================

name: Build rockchip armbian

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      set_release:
        description: "Select OS Release."
        required: false
        default: "jammy"
        type: choice
        options:
          - jammy
      armbian_soc:
        description: "Select rockchip SoC."
        required: false
        default: "all"
        type: choice
        options:
          - all
          - rock5b
          - beikeyun
          - l1pro
      armbian_kernel:
        description: "Select kernel version."
        required: false
        default: "5.10.150_5.15.75"
        type: choice
        options:
          - 5.4.210_5.10.150_5.15.75
          - 5.4.210_5.10.150
          - 5.10.150_5.15.75
          - 5.15.75_6.0.5
          - 5.4.210
          - 5.10.150
          - 5.15.75
          - 6.0.5
      auto_kernel:
        description: "Auto use the latest kernel."
        required: false
        default: true
        type: boolean
      armbian_size:
        description: "Set armbian rootfs size(Unit: MiB)."
        required: false
        default: "2560"
      armbian_fstype:
        description: "Select armbian rootfs type."
        required: false
        default: "ext4"
        type: choice
        options:
          - ext4
          - btrfs
      armbian_sign:
        description: "Set armbian custom name."
        required: false
        default: ""

env:
  TZ: America/New_York

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialization environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc 2>/dev/null
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install -y $(curl -fsSL https://is.gd/depend_ubuntu2204_armbian)
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "${TZ}"
          echo "ARMBIAN_RELEASE=${{ github.event.inputs.set_release }}" >> ${GITHUB_ENV}
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Download source code
        id: down
        if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
        run: |
          git clone --depth 1 https://github.com/armbian/build.git
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Compile Armbian [ ${{ env.ARMBIAN_RELEASE }} ]
        id: compile
        if: ${{ steps.down.outputs.status }} == 'success' && !cancelled()
        run: |
          # Compile method and parameter description: https://docs.armbian.com/Developer-Guide_Build-Options
          cd build/
          sudo ./compile.sh RELEASE=${{ env.ARMBIAN_RELEASE }} BOARD=rock-5b BRANCH=legacy BUILD_DESKTOP=no HOST=armbian EXPERT=yes \
                            BUILD_MINIMAL=no KERNEL_ONLY=no KERNEL_CONFIGURE=no CLEAN_LEVEL=make,debs COMPRESS_OUTPUTIMAGE="sha,gz"
          echo "build_tag=Armbian_rockchip_${{ env.ARMBIAN_RELEASE }}_$(date +"%m.%d.%H%M")" >> ${GITHUB_OUTPUT}
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Rebuild Armbian for rockchip
        uses: ophub/rockchip-armbian@main
        if: ${{ steps.compile.outputs.status }} == 'success' && !cancelled()
        with:
          armbian_path: build/output/images/*.img.gz
          armbian_soc: ${{ github.event.inputs.armbian_soc }}
          armbian_kernel: ${{ github.event.inputs.armbian_kernel }}
          auto_kernel: ${{ github.event.inputs.auto_kernel }}
          armbian_size: ${{ github.event.inputs.armbian_size }}
          armbian_fstype: ${{ github.event.inputs.armbian_fstype }}
          armbian_sign: ${{ github.event.inputs.armbian_sign }}

      - name: Upload Rebuild image to Release
        uses: ncipollo/release-action@main
        if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
        with:
          tag: ${{ steps.compile.outputs.build_tag }}
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allowUpdates: true
          token: ${{ secrets.GH_TOKEN }}
          body: |
            This is Armbian image for rockchip boxes
            * Firmware information
            Default username: root
            Default password: 1234
            Update command: armbian-update
