#==========================================================================
# Description: Build Armbian
# Copyright (C) 2021 https://github.com/ophub/amlogic-s9xxx-armbian
#==========================================================================

name: Rebuild armbian

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      armbian_url:
        description: "Set armbian path."
        required: false
        default: ""
      armbian_board:
        description: "Select Amlogic Board."
        required: false
        default: "all"
        type: choice
        options:
          - all
          - s922x_s905x3_s905d_s912_s905l3a
          - rock5b_r66s_r68s_beikeyun_l1pro
          - a311d
          - s922x
          - s922x-n2
          - s922x-reva
          - s905x3
          - s905x3-b
          - s905x2
          - s905x2-km3
          - s912
          - s912-m8s
          - s912-t95z-plus
          - s905d
          - s905d-ki
          - s905x
          - s905x-t95
          - s905w
          - s905
          - s905l3a
          - s905l2
          - s905lb-r3300l
          - rock5b
          - r66s
          - r68s
          - beikeyun
          - l1pro
          - eaidk-610
      armbian_kernel:
        description: "Select kernel version."
        required: false
        default: "5.15.85_6.1.1"
        type: choice
        options:
          - 5.4.225_5.10.160_5.15.85
          - 5.4.225_5.10.160
          - 5.10.160_5.15.85
          - 5.15.85_6.1.1
          - 5.4.225
          - 5.10.160
          - 5.15.85
          - 6.1.1
      auto_kernel:
        description: "Auto use the latest kernel."
        required: false
        default: true
        type: boolean
      kernel_repo:
        description: "Set the kernel repository."
        required: false
        default: "https://github.com/ophub/kernel/tree/main/pub"
      armbian_size:
        description: "Set armbian rootfs size(Unit: MiB)."
        required: false
        default: "2560"
      armbian_fstype:
        description: "Set armbian rootfs type."
        required: false
        default: "ext4"
        type: choice
        options:
          - ext4
          - btrfs
      armbian_sign:
        description: "Set armbian custom name."
        required: false
        default: ""

env:
  TZ: America/New_York

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialization environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android 2>/dev/null
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mongodb* dotnet* moby* snapd* || true
          sudo -E apt-get -qq update -y
          sudo -E apt-get -qq full-upgrade -y
          sudo -E apt-get -qq install -y $(curl -fsSL https://is.gd/depend_ubuntu2204_armbian)
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean

          # Get the url of the rebuild armbian file
          armbian_url="${{ inputs.armbian_url }}"
          if  [[ -z "${armbian_url}" ]]; then
              armbian_site="https://armbian.tnahosting.net/dl/odroidn2/archive/"
              armbian_name="Armbian.*jammy.*.img.xz"
              armbian_file=$(curl -s "${armbian_site}" | grep -oE "${armbian_name}" | head -n 1)
              if [[ -n "${armbian_file}" ]]; then
                  armbian_url="${armbian_site}${armbian_file}"
              else
                  echo -e "Invalid download path: [ ${armbian_site} ]"
                  exit 1
              fi
          fi
          echo "ARMBIAN_URL=${armbian_url}" >> ${GITHUB_ENV}

          # Get the release name of the rebuild armbian file
          set_release="_"
          ARR_RELEASE=("jammy" "focal" "bullseye" "buster" "sid")
          i=1
          for r in ${ARR_RELEASE[*]}; do
              if [[ "${armbian_url}" == *"${r}"* ]]; then
                  set_release="_${r}_"
                  break
              fi
              let i++
          done
          echo "ARMBIAN_RELEASE=${set_release}" >> ${GITHUB_ENV}
          sudo timedatectl set-timezone "${TZ}"
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Rebuild Armbian
        uses: ophub/amlogic-s9xxx-armbian@main
        if: ${{ env.ARMBIAN_URL }} != '' && !cancelled()
        with:
          build_target: armbian
          armbian_path: ${{ env.ARMBIAN_URL }}
          armbian_board: ${{ inputs.armbian_board }}
          armbian_kernel: ${{ inputs.armbian_kernel }}
          auto_kernel: ${{ inputs.auto_kernel }}
          kernel_repo: ${{ inputs.kernel_repo }}
          armbian_size: ${{ inputs.armbian_size }}
          armbian_fstype: ${{ inputs.armbian_fstype }}
          armbian_sign: ${{ inputs.armbian_sign }}
          gh_token: ${{ secrets.GH_TOKEN }}

      - name: Upload Armbian image to Release
        uses: ncipollo/release-action@main
        if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
        with:
          tag: Armbian${{ env.ARMBIAN_RELEASE }}${{ env.PACKAGED_OUTPUTDATE }}
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allowUpdates: true
          token: ${{ secrets.GH_TOKEN }}
          body: |
            These are the Armbian OS image
            * OS information
            Default username: root
            Default password: 1234
            Install command: armbian-install
            Update command: armbian-update
