#==========================================================================
# Description: Build Armbian For Amlogic s9xxx tv box
# Copyright (C) 2021 https://github.com/ophub/amlogic-s9xxx-armbian
#==========================================================================

name: Rebuild armbian

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      armbian_url:
        description: "Set armbian path."
        required: false
        default: ""
      armbian_soc:
        description: "Select Amlogic SoC."
        required: false
        default: "s905x3_s905d_s912"
        type: choice
        options:
          - all
          - s905x3_s905d_s912
          - a311d
          - s922x
          - s922x-n2
          - s922x-reva
          - s905x3
          - s905x2
          - s905x2-km3
          - s912
          - s912-m8s
          - s905d
          - s905d-ki
          - s905x
          - s905w
          - s905
          - s905l3a
      armbian_kernel:
        description: "Select kernel version."
        required: false
        default: "5.10.135_5.15.50"
        type: choice
        options:
          - 5.4.210_5.10.135_5.15.50
          - 5.4.210_5.10.135
          - 5.10.135_5.15.50
          - 5.15.50_5.19.1
          - 5.4.210
          - 5.10.135
          - 5.15.50
          - 5.19.1
      auto_kernel:
        description: "Auto use the latest kernel."
        required: false
        default: true
        type: boolean
      armbian_size:
        description: "Set armbian rootfs size(Unit: MiB)."
        required: false
        default: "2560"
      armbian_fstype:
        description: "Set armbian rootfs type."
        required: false
        default: "ext4"
        type: choice
        options:
          - ext4
          - btrfs
      armbian_sign:
        description: "Set armbian custom name."
        required: false
        default: ""

env:
  TZ: America/New_York

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialization environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc 2>/dev/null
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install -y $(curl -fsSL https://is.gd/depend_ubuntu2204_armbian)
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "${TZ}"

          # Get the url of the rebuild armbian file
          armbian_url="${{ github.event.inputs.armbian_url }}"
          if  [[ -z "${armbian_url}" ]]; then
              armbian_site="https://armbian.tnahosting.net/dl/odroidn2/archive/"
              armbian_name="Armbian.*jammy.*.img.xz"
              armbian_file=$(curl -s "${armbian_site}" | grep -oE "${armbian_name}" | head -n 1)
              if [[ -n "${armbian_file}" ]]; then
                  armbian_url="${armbian_site}${armbian_file}"
              else
                  echo -e "Invalid download path: [ ${armbian_site} ]"
                  exit 1
              fi
          fi
          echo "ARMBIAN_URL=${armbian_url}" >> $GITHUB_ENV

          # Get the release name of the rebuild armbian file
          set_release="_"
          ARR_RELEASE=("jammy" "focal" "bullseye" "buster" "sid")
          i=1
          for r in ${ARR_RELEASE[*]}; do
              if [[ "${armbian_url}" == *"${r}"* ]]; then
                  set_release="_${r}_"
                  break
              fi
              let i++
          done
          echo "ARMBIAN_RELEASE=${set_release}" >> $GITHUB_ENV
          echo "::set-output name=status::success"

      - name: Rebuild Armbian for Amlogic s9xxx
        uses: ophub/amlogic-s9xxx-armbian@main
        if: env.ARMBIAN_URL != '' && !cancelled()
        with:
          build_target: armbian
          armbian_path: ${{ env.ARMBIAN_URL }}
          armbian_soc: ${{ github.event.inputs.armbian_soc }}
          armbian_kernel: ${{ github.event.inputs.armbian_kernel }}
          auto_kernel: ${{ github.event.inputs.auto_kernel }}
          armbian_size: ${{ github.event.inputs.armbian_size }}
          armbian_fstype: ${{ github.event.inputs.armbian_fstype }}
          armbian_sign: ${{ github.event.inputs.armbian_sign }}

      - name: Upload Armbian image to Release
        uses: ncipollo/release-action@main
        if: env.PACKAGED_STATUS == 'success' && !cancelled()
        with:
          tag: Armbian_Aml${{ env.ARMBIAN_RELEASE }}${{ env.PACKAGED_OUTPUTDATE }}
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allowUpdates: true
          token: ${{ secrets.GH_TOKEN }}
          body: |
            This is Armbian image for Amlogic s9xxx tv box
            * Firmware information
            Default username: root
            Default password: 1234
            Install command: armbian-install
            Update command: armbian-update
